# -*- coding: utf-8 -*-
"""food_process.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eGuqOw5QzOCKhMybO0VC7rVZpqt-JjcM
"""

import pandas as pd
import numpy as np

pd.set_option("mode.copy_on_write", True)

# file path to the dataset
file_path = "/Users/tinayiluo/Desktop/food.csv"

# Reading the csv
df = pd.read_csv(file_path)

df.head()

df

original_columns = [
    "Category",
    "Description",
    "Nutrient Data Bank Number",
    "Data.Alpha Carotene",
    "Data.Beta Carotene",
    "Data.Beta Cryptoxanthin",
    "Data.Carbohydrate",
    "Data.Cholesterol",
    "Data.Choline",
    "Data.Fiber",
    "Data.Lutein and Zeaxanthin",
    "Data.Lycopene",
    "Data.Niacin",
    "Data.Protein",
    "Data.Retinol",
    "Data.Riboflavin",
    "Data.Selenium",
    "Data.Sugar Total",
    "Data.Thiamin",
    "Data.Water",
    "Data.Fat.Monosaturated Fat",
    "Data.Fat.Polysaturated Fat",
    "Data.Fat.Saturated Fat",
    "Data.Fat.Total Lipid",
    "Data.Major Minerals.Calcium",
    "Data.Major Minerals.Copper",
    "Data.Major Minerals.Iron",
    "Data.Major Minerals.Magnesium",
    "Data.Major Minerals.Phosphorus",
    "Data.Major Minerals.Potassium",
    "Data.Major Minerals.Sodium",
    "Data.Major Minerals.Zinc",
    "Data.Vitamins.Vitamin A - RAE",
    "Data.Vitamins.Vitamin B12",
    "Data.Vitamins.Vitamin B6",
    "Data.Vitamins.Vitamin C",
    "Data.Vitamins.Vitamin E",
    "Data.Vitamins.Vitamin K",
]

revised_columns = [
    col.replace(" ", "_").replace(".", "_").replace("-", "_")
    for col in original_columns
]

# Now, to rename the DataFrame columns, you would use:
df.columns = revised_columns

df.head()

# Drop the 'Description' and 'Nutrient Data Bank Number' columns
df = df.drop(["Description", "Nutrient_Data_Bank_Number"], axis=1)

df.head()

# Group by 'Category' and calculate the mean for each group
category_averages = df.groupby("Category").mean()

# Count unique values in the 'Category' column
category_counts = df["Category"].value_counts()

# Display the counts for each unique entry in 'Category'
print(category_counts)

category_averages

category_averages.head()

# Export 'category_averages' DataFrame to a CSV file
category_averages.to_csv("food_new.csv", index=True)